
[package]
name = "chaosregen"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your@email.com>"]
description = "ChaosRegen: Lossless entropy compression based on universal constants and modular math."
license = "MIT"

[dependencies]
rand = "0.8"
